extends RefCounted
class_name __EffectSignals

@warning_ignore("unused_signal") signal change_max_life(max_life: int)
@warning_ignore("unused_signal") signal change_revives(revives: int)
@warning_ignore("unused_signal") signal change_defense(defense: int)
@warning_ignore("unused_signal") signal change_coins(coins: int)
@warning_ignore("unused_signal") signal quest_start()
@warning_ignore("unused_signal") signal quest_finish()
@warning_ignore("unused_signal") signal damage(amount: int, source: Object)
@warning_ignore("unused_signal") signal change_life(amount: int, source: Object)
@warning_ignore("unused_signal") signal death(source: Object)
@warning_ignore("unused_signal") signal player_lose(source: Object)
@warning_ignore("unused_signal") signal spend_coins(amount: int, dest: Object)
@warning_ignore("unused_signal") signal change_score(score: int)
@warning_ignore("unused_signal") signal change_cells_opened_since_mistake(cells_opened_since_mistake: int)
@warning_ignore("unused_signal") signal change_morality(morality: int)
@warning_ignore("unused_signal") signal change_chests_opened(chests_opened: int)
@warning_ignore("unused_signal") signal change_monsters_killed(monsters_killed: int)
@warning_ignore("unused_signal") signal get_coin_value(value: int, cell: Cell)
@warning_ignore("unused_signal") signal get_diamond_value(value: int, cell: Cell)
@warning_ignore("unused_signal") signal get_chest_reward_count(reward_count: int, cell: Cell)
@warning_ignore("unused_signal") signal get_chest_item_max_cost(max_cost: int, cell: Cell)
@warning_ignore("unused_signal") signal item_use(item: Item)
@warning_ignore("unused_signal") signal get_chest_rewards(rewards: Variant)
@warning_ignore("unused_signal") signal cell_open(cell: Cell)
@warning_ignore("unused_signal") signal item_gain(item: Item)
@warning_ignore("unused_signal") signal inventory_add_item(item: Item)
@warning_ignore("unused_signal") signal item_lose(item: Item)
@warning_ignore("unused_signal") signal get_string_table(table: StringTable)
@warning_ignore("unused_signal") signal get_shop_item_count(item_count: int)
@warning_ignore("unused_signal") signal restore_life(life: int, source: Object)
@warning_ignore("unused_signal") signal lose_life(life: int, source: Object)
