extends RefCounted
class_name __EffectSignals

@warning_ignore("unused_signal") signal board_permissions_changed()
@warning_ignore("unused_signal") signal bury_bones(cell: Cell)
@warning_ignore("unused_signal") signal get_aura_color(default: Color, aura: String, cell: Cell)
@warning_ignore("unused_signal") signal turn()
@warning_ignore("unused_signal") signal cell_open(cell: Cell)
@warning_ignore("unused_signal") signal cell_get_mana(default: int, cell: Cell)
@warning_ignore("unused_signal") signal get_chest_reward_count(default: int, cell: Cell)
@warning_ignore("unused_signal") signal get_chest_item_max_cost(default: int, cell: Cell)
@warning_ignore("unused_signal") signal player_lose(source: Object)
@warning_ignore("unused_signal") signal get_diamond_value(default: int, cell: Cell)
@warning_ignore("unused_signal") signal get_coin_value(default: int, cell: Cell)
@warning_ignore("unused_signal") signal stage_leave()
@warning_ignore("unused_signal") signal mistake()
@warning_ignore("unused_signal") signal stage_enter()
@warning_ignore("unused_signal") signal board_loaded()
@warning_ignore("unused_signal") signal board_begin()
@warning_ignore("unused_signal") signal stage_load()
@warning_ignore("unused_signal") signal get_string_table(default: Object, table_name: String)
@warning_ignore("unused_signal") signal quest_start()
@warning_ignore("unused_signal") signal quest_finish()
@warning_ignore("unused_signal") signal change_score(score: int)
@warning_ignore("unused_signal") signal change_cells_opened_since_mistake(new_argument: int)
@warning_ignore("unused_signal") signal change_morality(morality: int)
@warning_ignore("unused_signal") signal change_chests_opened(chests_opened: int)
@warning_ignore("unused_signal") signal change_monsters_killed(monsters_killed: int)
@warning_ignore("unused_signal") signal change_pathfinding(pathfinding: int)
@warning_ignore("unused_signal") signal item_use(new_argument: Object)
@warning_ignore("unused_signal") signal parse_icon_atlas(atlas: AtlasTexture, name: String)
@warning_ignore("unused_signal") signal parse_icon_rect(rect: Rect2i, name: String)
@warning_ignore("unused_signal") signal change_coins(coins: int, source: Object)
@warning_ignore("unused_signal") signal get_shop_item_count(default: int)
@warning_ignore("unused_signal") signal change_max_life(max_life: int)
@warning_ignore("unused_signal") signal change_revives(revives: int)
@warning_ignore("unused_signal") signal change_defense(defense: int)
@warning_ignore("unused_signal") signal damage(amount: int, source: Object)
@warning_ignore("unused_signal") signal change_life(life: int)
@warning_ignore("unused_signal") signal death(source: Object)
@warning_ignore("unused_signal") signal spend_coins(amount: int, destination: Object)
@warning_ignore("unused_signal") signal item_gain(item: Object)
@warning_ignore("unused_signal") signal inventory_add_item(item: Object)
@warning_ignore("unused_signal") signal item_lose(item: Object)
